from odoo import fields, models


class MailActivity(models.Model):
    _inherit = "mail.activity"

    ob_ai_generated = fields.Boolean(string="Generated by AI Assistant", copy=False, index=True)
    ob_ai_idempotency_key = fields.Char(string="AI Idempotency Key", copy=False, index=True)
