from . import ir_attachment
from . import ob_ocr_document
from . import ob_ocr_document_line
from . import ob_ocr_document_type
from . import ob_ocr_extraction_rule
from . import ob_ocr_log
from . import ob_ocr_mapping
from . import ob_ocr_mapping_field
from . import ob_ocr_provider
from . import res_config_settings
